
###  Petición sin especificar la ruta
# Esperado: Código de estado 400 Bad Request y mensaje "La ruta no fue especificada"
GET http://localhost:80/api/public/


### Petición a una ruta válida (auth)
# Esperado: El contenido que genere src/routes/user.php (y un código 200 OK si todo va bien)
GET   http://localhost:80/api/public/auth


### Petición a una ruta válida (user)
# Esperado: El contenido que genere src/routes/user.php (y un código 200 OK si todo va bien)
GET http://localhost:80/api/public/index.php?laRuta=auth


### Petición a una ruta válida (user)
# Esperado: El contenido que genere src/routes/user.php (y un código 200 OK si todo va bien)
GET http://localhost:80/api/public/user


### Petición a una ruta válida (user)
# Esperado: El contenido que genere src/routes/user.php (y un código 200 OK si todo va bien)
GET http://localhost:80/api/public/index.php?laRuta=user

### 
GET  http://localhost:8000/api/estudiantes/listar

content-type: application/json 

{
    
}


### 
post http://localhost:8000/api/estudiante

content-type: application/json

{
 
    "nombre": "require",
    "telefono": "require",
    "email": "require|email",
    "lenguaje": "require",
}
